name: firebase_validation
description: Plugin usado pela empresa CGI Software para validação de dados
version: 1.0.4
homepage: http://www.webcgi.com.br

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.8
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  device_info: ^0.4.2+4
  url_launcher: ^5.5.3
  flutter_html: ^1.0.2
  package_info: ^0.4.1
  intl: ^0.16.1
  dio: ^3.0.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:

    android:
      package: io.github.cgisoftware.firebase_validation
      pluginClass: FirebaseValidationPlugin
    ios:
      pluginClass: FirebaseValidationPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
